# Analyzers

Currently, there are several analyzers available within the app:  

1. The HM-Model/Changepoint (1 QPD) analyzer was designed for single molecule trapping data
2. Covariance (2 QPD) also for single molecule data
3. Force Balance for force ramp protocols 
4. Isometric Force Clamp (self-named)
5. Mini-Ensemble analyzer (self-named) 

These analyzers have a similar UI with the ability to impose user control over some of the analysis parameters. 

For all analyzers, you have the option to run the analyzer through all of the observations in a given date folder, or you can select just a single observation. If you select to analyze a single observation you must also select the observation you want to analyze in the Folder Navigator (top right button). 

## HM-Model/Changepoint (1 QPD)

Intended for single molecule data, this analyzer uses a combination approach to identify single molecule binding events. A Hidden Markov Model is implemented with the [{depmixS4}](https://cran.r-project.org/web/packages/depmixS4/vignettes/depmixS4.pdf) R-package on a running window transformation of the data to estimate locations of binding events. Then a changepoint analysis is applied to a small subset of the original trapping data around the HM-Model estimated transition periods with the [{changepoint}](https://www.jstatsoft.org/article/view/v058i03) R-package to precisely choose the most probable data point (at the original sampling frequency) where the binding event occurred.

Within the HM-Model/Changepoint analyzer, users have control (to some extent) over most aspects of the analyzer including the running window transformations, some of the HM-Model, and the type of changepoint. 

Clicking the "Options" button will open up a menu that will allow you to set the analysis option. 

### Options: HM-Model

The Hidden Markov Model analyzes a running window transformation of the original data trace. Here you can select the window width (in data points) and how you would like the window to progress. Users are referenced to [Smith, Steffon, Simmons, and Sleep 2001](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1301746/pdf/11606292.pdf) for further details on how to optimize the windows. Per their recommendations the default of the progression of the windows is by 1/2 overlap. **Note: not all window slide options have been tested. Possible bugs may exist and app crash potential**. You can just restart the app and try another option. 

The "Channels" options lets you choose if you want the Hidden Markov Model to use both the running mean AND running variance transformations or just the running variance. A personal anecdotal recommendation is to use both the running mean and variance. 

"EM Random Start" is `FALSE` (unchecked) by default. If `TRUE` (checked) the analyzer will use random number generation to start the EM-Algorithm. 

### Options: Changepoint

There are two sections the changepoint options. Since changepoint analysis is applied separately to the beginning and ends of the events so you can control the behavior of both. The default is to use the changepoint method "Mean/Var" which has the changepoint algorithm use the mean and variance position to identify the most probable change. Whereas if "Variance" is selected a slider will appear allowing the user to select a window width for the running variance transformation. The changepoint will then look for a change in the mean signal position of the variance transformation to identify the most probable change. 

### Options: Displacements

Users can select one of two methods for peak displacements to be calculated. The "average" method calculates the mean signal position of the entire ID'd event minus the first and last 5ms. Alternatively, users can opt to use the "peak" method which returns a maximum value from a 5ms running mean of the ID'd event. 


## Covariance (2 QPD)

The covariance analyzer is for single molecule experiments collected on systems with 2 QPDs.

Very similar to the HM-Model/Changepoint (1 QPD) except replaces the variance dimension with covariance between the beads position. This provides event displacement, force, and time on calculations for every event in both data traces (bead 1 and bead 2). You can take the average of both signal's values or select one or the other to report. Just make sure to properly deal with this in your summary calculations.


## Force Balance

This is the exact analyzer as the HM-Model/Changepoint (1 QPD) analysis without "direction correction" and with the addition for the "force balance" metric. This analysis is used with force ramping protocols, like waving an actin filament over a load dependent actin binding protein. As one bead is pulled out of its trap, the other bead relaxes to the center of its trap. Users first select the "preferred bead" in clean and process where the displacements are largest or most visible. The analyzer identifies events in the "preferred channel" and then goes into the "other" bead channel and calculates its relative displacements/force. Then the "preferred" signal force and "other" force are subtracted to provide a "force balance" system force that is experienced by the protein. 

The "other" force/displacement is calculated over a 5 ms datapoint window surrounding the "peak-nm-index" metric determined from the preferred bead.

The Force Balance requires a "preferred channel" to be selected in clean and process.

### Options: Force Balance


Same as HM-Model/Changepoint (1 QPD).

## Mini-Ensemble

This mini-ensemble analyzer uses a simple thresholding method to ID events. Users can control the threshold parameters for the displacement and minimum time on as well as the running window width. 

### Options: Mini-ensemble

Click on the "Advanced" toggle switch to display a few parameters that you can change for the mini-ensemble analysis.

**Running Mean Window Width**: the number of milliseconds to use for the running mean window. Note, this running mean window will be calculated and advance one datapoint at a time.
**Set Displacement Threshold**: the number of nanometers to apply the threshold at. Anytime the running mean goes above this threshold, it is scored as an event.
**Set Minimum Time Threshold**: the minimum number of milliseconds needed for the event to considered an "event". Once the running mean goes over the displacement threshold it is counted as an event. After all these events are counted, they are then filtered so that only events that are greater in time duration than this minimum time duration as retained as events. 

### Notes about mini analyzer

The Mini-ensemble analyzer actually analyzes every trace twice. The first time to ID events as-is in the Clean & Processed Data. Then, it performs a baseline correction where the average baseline position before every event is calculated and subtracted from the baseline+the following event. The rationale for this was to account for small position drift over time. Even though the signal is baseline corrected in Clean & Process, sometimes baseline does not go back to 0. It might be +0.5 nm or -0.25 nm etc. So, this is an additional small adjustment to make sure peak displacement are not over or underestimated by starting from a non-zero value. 

Example, let's say a 30 nm peak displacement is measured, but the baseline started at +2nm. So first, this event is identified by the first analysis, then baseline corrected so the baseline and event are subtracted by -2 nm, which shifts the baseline back to 0nm and the peak down to 28nm. After this is performed throughout the whole trace, the events are re-identified and analyzed again to extract this new information which results in an event peak displacement of 28 nm. This does not occur in the single molecule analyzers because those use relative displacement changes, whereas the mini ensemble is an absolute displacement measurement.


## Isometric Force Clamp

The Isometric Force Clamp analyzer only works with 2-channel datasets. It works by applying a 2-state hidden markov model to the motor bead position to identify the binding events. The average force of the event and the corresponding lifetime are saved in the output files. After analyzing all your data, you can use the "Summarize" tab to fit the Bell-bond equation to this resulting data. 

There is also an analyzer for the isometric force clamp, a feedback experiment, requires 2 bead signals and a "Feedback motor bead" designated when uploading data.

### Options: HM-Model

You can select the window width (in data points) and window slide, along with "EM Random Start" (see above).

## Review

You can run any data through any analyses and get some numbers as a result. But do the numbers mean something? Do the numbers make sense? Users of *lasertrapr* are recommended to do what we do: visually inspect every identified event in every data trace to assess the validity of the analysis. If this analysis appears correct, select "Yes" for "Should this analysis be accepted?" (i.e. review = TRUE). This does not delete any data, but allows the application to know which data to include in summary calculations or ensemble averages. It is just adding a TRUE/FALSE column to filter on in "option.csv".

You can also filter out individual event with "Review options" button.

The "snapshot" buttom (camera icon) allows you to export data plots with highlighted events. Notably, you can export RDS files which are ggplot object which is how we make our figures for our papers.

## tl;dr

Just show me a video...

<video width="800" height="400" controls>
  <source src="images/analyzer.mp4" type="video/mp4">
Your browser does not support the video tag.
</video>
